# Generated by Django 5.1 on 2024-09-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
