# Generated by Django 5.1 on 2024-09-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_works'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='w_description',
            new_name='w_description_one',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='w_name',
            new_name='w_name_one',
        ),
    ]
