# Generated by Django 5.1 on 2024-10-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_one_title', models.CharField(max_length=500)),
                ('w_one_description', models.CharField(max_length=500)),
                ('w_two_title', models.CharField(max_length=500)),
                ('w_two_description', models.CharField(max_length=500)),
                ('w_three_title', models.CharField(max_length=500)),
                ('w_three_description', models.CharField(max_length=500)),
                ('w_four_title', models.CharField(max_length=500)),
                ('w_four_description', models.CharField(max_length=500)),
            ],
        ),
    ]
