# Generated by Django 5.1 on 2024-10-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_works'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='w_four_description',
            new_name='w_description',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='w_four_title',
            new_name='w_title',
        ),
        migrations.RemoveField(
            model_name='works',
            name='w_one_description',
        ),
        migrations.RemoveField(
            model_name='works',
            name='w_one_title',
        ),
        migrations.RemoveField(
            model_name='works',
            name='w_three_description',
        ),
        migrations.RemoveField(
            model_name='works',
            name='w_three_title',
        ),
        migrations.RemoveField(
            model_name='works',
            name='w_two_description',
        ),
        migrations.RemoveField(
            model_name='works',
            name='w_two_title',
        ),
    ]
