# Generated by Django 5.1 on 2024-10-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_rename_w_four_description_works_w_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_description', models.CharField(max_length=500)),
                ('a_name', models.CharField(max_length=500)),
                ('a_age', models.CharField(max_length=500)),
                ('a_occupation', models.CharField(max_length=500)),
                ('a_phone', models.CharField(max_length=500)),
                ('a_email', models.CharField(max_length=500)),
                ('a_nationality', models.CharField(max_length=500)),
            ],
        ),
    ]
