# Generated by Django 5.1 on 2024-10-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_title', models.CharField(max_length=500)),
                ('d_institution', models.CharField(max_length=500)),
                ('e_description', models.CharField(max_length=500)),
            ],
        ),
    ]
