# Generated by Django 5.1 on 2024-10-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_degree_d_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Degree',
            new_name='Degrees',
        ),
        migrations.RenameField(
            model_name='degrees',
            old_name='e_description',
            new_name='d_description',
        ),
    ]
