# Generated by Django 5.1 on 2024-10-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_rename_degree_degrees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_description', models.CharField(max_length=500)),
            ],
        ),
    ]
