# Generated by Django 5.1 on 2024-10-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_aexperience_rename_experiences_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AExperience',
        ),
    ]
