# Generated by Django 5.1 on 2024-10-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_aexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_description', models.CharField(max_length=500)),
            ],
        ),
    ]
