# Generated by Django 5.1 on 2024-10-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='AResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_ex_title', models.CharField(max_length=500)),
                ('a_ex_duration', models.CharField(max_length=500)),
                ('a_ex_description', models.CharField(max_length=500)),
            ],
        ),
    ]
