# Generated by Django 5.1 on 2024-10-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_aresearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aresearch',
            old_name='a_ex_description',
            new_name='a_res_description',
        ),
        migrations.RenameField(
            model_name='aresearch',
            old_name='a_ex_duration',
            new_name='a_res_duration',
        ),
        migrations.RenameField(
            model_name='aresearch',
            old_name='a_ex_title',
            new_name='a_res_title',
        ),
    ]
