# Generated by Django 5.1 on 2024-10-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_rename_a_ex_description_aresearch_a_res_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ff_description', models.CharField(max_length=500)),
            ],
        ),
    ]
