# Generated by Django 5.1 on 2024-10-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_fun'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_number', models.CharField(max_length=500)),
                ('f_lno', models.CharField(max_length=500)),
                ('f_lnt', models.CharField(max_length=500)),
            ],
        ),
    ]
