# Generated by Django 5.1 on 2024-10-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_s_perc', models.CharField(max_length=500)),
                ('a_s_title', models.CharField(max_length=500)),
            ],
        ),
    ]
