# Generated by Django 5.1 on 2024-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_askill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_description', models.CharField(max_length=500)),
            ],
        ),
    ]
