# Generated by Django 5.1 on 2024-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0022_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=500)),
                ('f_designation', models.CharField(max_length=500)),
                ('f_company', models.CharField(max_length=500)),
                ('f_feed', models.CharField(max_length=500)),
            ],
        ),
    ]
