# Generated by Django 5.1 on 2024-10-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0023_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_title', models.CharField(max_length=500)),
                ('w_description', models.CharField(max_length=500)),
            ],
        ),
    ]
