# Generated by Django 5.1 on 2024-10-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0025_tservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TService',
            new_name='Service',
        ),
    ]
