# Generated by Django 5.1 on 2024-10-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0026_rename_tservice_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='w_description',
            new_name='s_description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='w_title',
            new_name='s_title',
        ),
    ]
