# Generated by Django 5.1 on 2024-10-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0027_rename_w_description_services_s_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cntc_t', models.CharField(max_length=500)),
            ],
        ),
    ]
