# Generated by Django 5.1 on 2024-10-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0028_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cntc_address', models.CharField(max_length=500)),
                ('cntc_number', models.CharField(max_length=500)),
                ('cntc_email', models.CharField(max_length=500)),
            ],
        ),
    ]
