# Generated by Django 5.1 on 2024-11-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0029_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='i_image',
            field=models.ImageField(default=1, upload_to='i_image'),
            preserve_default=False,
        ),
    ]
