# Generated by Django 5.1 on 2024-09-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('a_age', models.CharField(max_length=50)),
                ('a_occupation', models.CharField(max_length=100)),
                ('a_phone', models.CharField(max_length=50)),
                ('a_email', models.CharField(max_length=50)),
                ('a_nationality', models.CharField(max_length=100)),
                ('a_description', models.CharField(max_length=500)),
            ],
        ),
    ]
