# Generated by Django 5.1 on 2024-09-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_rename_a_name_intro_i_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_title', models.CharField(max_length=100)),
                ('d_description', models.CharField(max_length=100)),
            ],
        ),
    ]
