# Generated by Django 5.1 on 2024-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_dbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_w_title', models.CharField(max_length=100)),
                ('s_w_description', models.CharField(max_length=100)),
            ],
        ),
    ]
