# Generated by Django 5.1 on 2024-09-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_description', models.CharField(max_length=100)),
            ],
        ),
    ]
