# Generated by Django 5.1 on 2024-09-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0008_edud'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_title', models.CharField(max_length=100)),
                ('f_institute', models.CharField(max_length=100)),
                ('f_description', models.CharField(max_length=100)),
            ],
        ),
    ]
