# Generated by Django 5.1 on 2024-09-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0009_fdeg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScDeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_title', models.CharField(max_length=100)),
                ('sc_institute', models.CharField(max_length=100)),
                ('sc_description', models.CharField(max_length=100)),
            ],
        ),
    ]
