# Generated by Django 5.1 on 2024-09-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0010_scdeg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThdDeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thd_title', models.CharField(max_length=100)),
                ('thd_institute', models.CharField(max_length=100)),
                ('thd_description', models.CharField(max_length=100)),
            ],
        ),
    ]
