# Generated by Django 5.1 on 2024-09-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0017_lappy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lappy',
            old_name='face_description',
            new_name='lp_description',
        ),
    ]
