# Generated by Django 5.1 on 2024-09-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0018_rename_face_description_lappy_lp_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp_description', models.CharField(max_length=100)),
            ],
        ),
    ]
