# Generated by Django 5.1 on 2024-09-29 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0019_ug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ug',
            old_name='lp_description',
            new_name='ug_description',
        ),
    ]
