# Generated by Django 5.1 on 2024-09-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0020_rename_lp_description_ug_ug_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_e',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_e_description', models.CharField(max_length=100)),
            ],
        ),
    ]
