# Generated by Django 5.1 on 2024-09-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0021_m_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_ex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_ex_title', models.CharField(max_length=100)),
                ('f_ex_institute', models.CharField(max_length=100)),
                ('f_ex_description', models.CharField(max_length=100)),
            ],
        ),
    ]
