# Generated by Django 5.1 on 2024-09-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0022_f_ex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_title', models.CharField(max_length=100)),
                ('pm_institute', models.CharField(max_length=100)),
                ('pm_description', models.CharField(max_length=100)),
            ],
        ),
    ]
