# Generated by Django 5.1 on 2024-09-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0023_pm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_title', models.CharField(max_length=100)),
                ('sd_institute', models.CharField(max_length=100)),
                ('sd_description', models.CharField(max_length=100)),
            ],
        ),
    ]
