# Generated by Django 5.1 on 2024-09-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0024_sd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_description', models.CharField(max_length=100)),
            ],
        ),
    ]
