# Generated by Django 5.1 on 2024-09-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0025_rp'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_rch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_rch_title', models.CharField(max_length=100)),
                ('f_rch_description', models.CharField(max_length=100)),
            ],
        ),
    ]
