# Generated by Django 5.1 on 2024-09-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0031_thd_rch_dr'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_rch_dr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_rch_dr', models.CharField(max_length=100)),
            ],
        ),
    ]
