# Generated by Django 5.1 on 2024-09-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0034_f_ex_dr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pm_dr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_duration', models.CharField(max_length=100)),
            ],
        ),
    ]
