# Generated by Django 5.1 on 2024-09-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0036_rename_pm_duration_pm_dr_pm_dr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pm_dr',
            old_name='pm_dr',
            new_name='pm_duration',
        ),
    ]
