# Generated by Django 5.1 on 2024-09-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0037_rename_pm_dr_pm_dr_pm_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sd_dr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_duration', models.CharField(max_length=100)),
            ],
        ),
    ]
