# Generated by Django 5.1 on 2024-09-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0038_sd_dr'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_dr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_duration', models.CharField(max_length=100)),
            ],
        ),
    ]
