# Generated by Django 5.1 on 2024-09-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0040_sc_dr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc_dr',
            old_name='sc_duration',
            new_name='sc_dur',
        ),
    ]
