# Generated by Django 5.1 on 2024-09-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0041_rename_sc_duration_sc_dr_sc_dur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sc_dr',
        ),
    ]
