# Generated by Django 5.1 on 2024-09-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0044_thd_dr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fft_rch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fft_rch_title', models.CharField(max_length=100)),
                ('fft_rch_duration', models.CharField(max_length=100)),
                ('sd_description', models.CharField(max_length=100)),
            ],
        ),
    ]
