# Generated by Django 5.1 on 2024-09-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0045_fft_rch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fft_rch',
            old_name='sd_description',
            new_name='fft_rch_description',
        ),
    ]
