# Generated by Django 5.1 on 2024-09-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0046_rename_sd_description_fft_rch_fft_rch_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sxth_rch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sxth_rch_title', models.CharField(max_length=100)),
                ('sxth_rch_duration', models.CharField(max_length=100)),
                ('sxth_rch_description', models.CharField(max_length=100)),
            ],
        ),
    ]
