# Generated by Django 5.1 on 2024-09-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0051_thd_fn_fct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frt_fn_fct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frt_fn_fct_yrs', models.CharField(max_length=100)),
                ('frt_fn_fct_on_description', models.CharField(max_length=100)),
                ('frt_fn_fct_tw_description', models.CharField(max_length=100)),
            ],
        ),
    ]
